CREATE TABLE users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	first_name text NOT NULL,
	last_name text,
	password VARCHAR(255) NOT NULL,
	created_at timestamptz
)
